language: perl
services:
  - postgresql
perl:
  - "5.20"
  - "5.22"
before_install:
  - cpanm Devel::Cover Devel::Cover::Report::Coveralls
  - cpanm --quiet --installdeps --notest .
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - ./Build build
  - cover -test -report coveralls
