language: perl
sudo: false
perl:
  - "5.20"
  - "5.22"

befor_install:
  - cpanm Devel::Cover
  - perl Build.PL

install:
  - ./Build installdeps

script:
  - ./Build testcover
  - cover -report coveralls