language: perl
sudo: false
perl:
  - "5.20"
  - "5.22"

before_install:
  - cpanm Devel::Cover Devel::Cover::Report::Coveralls
  - cpanm --quiet --installdeps --notest .

script:
  - ./Build testcover
  - cover -report coveralls